version: 2.1

jobs:
  build_minimal:
    docker:
      - image: circleci/ruby:2.6.1
    steps:
      - checkout
      - setup_remote_docker
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t rubydata/minimal-notebook:latest minimal
            rev=`git rev-parse HEAD`
            docker tag rubydata/minimal-notebook:latest rubydata/minimal-notebook:${rev}
            docker push rubydata/minimal-notebook:${rev}
            docker push rubydata/minimal-notebook:latest

  build_datascience:
    docker:
      - image: circleci/ruby:2.6.1
    steps:
      - checkout
      - setup_remote_docker
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t rubydata/datascience:latest datascience
            rev=`git rev-parse HEAD`
            docker tag rubydata/datascience-notebook:latest rubydata/datascience-notebook:${rev}
            docker push rubydata/datascience-notebook:${rev}
            docker push rubydata/datascience-notebook:latest
